import { v4 as uuidv4 } from "https://jspm.dev/uuid";

const menuArray = [
  {
    name: "Sandwich",
    ingredients: ["turkey", "cheddar", "lettuce"],
    price: 7,
    emoji: "🥪",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
  {
    name: "Pasta",
    ingredients: ["spaghetti", "tomato sauce", "parmesan"],
    price: 10,
    emoji: "🍝",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
  {
    name: "Juice",
    ingredients: ["orange", "carrot", "apple"],
    price: 4,
    emoji: "🧃",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
  {
    name: "Burrito",
    ingredients: ["beans", "rice", "salsa"],
    price: 8,
    emoji: "🌯",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
  {
    name: "Ice Cream",
    ingredients: ["vanilla", "chocolate", "sprinkles"],
    price: 6,
    emoji: "🍨",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
  {
    name: "Wrap",
    ingredients: ["grilled chicken", "lettuce", "tomato"],
    price: 9,
    emoji: "🌯",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
  {
    name: "Soup",
    ingredients: ["vegetables", "broth", "noodles"],
    price: 5,
    emoji: "🍲",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
  {
    name: "Fruit Salad",
    ingredients: ["melon", "grapes", "kiwi"],
    price: 6,
    emoji: "🍇",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
  {
    name: "Muffin",
    ingredients: ["blueberry", "flour", "sugar"],
    price: 3.5,
    emoji: "🧁",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },

  {
    name: "Smoothie",
    ingredients: ["banana", "berries", "yogurt"],
    price: 5,
    emoji: "🥤",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
];

export default menuArray;
