import { v4 as uuidv4 } from "https://jspm.dev/uuid";

const menuArray = [
  {
    name: "Sandwich",
    ingredients: ["turkey", "cheddar", "lettuce"],
    price: 7,
    imageurl: "https://source.unsplash.com/IZ0LRt1khgM",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
  {
    name: "Pasta",
    ingredients: ["spaghetti", "tomato sauce", "parmesan"],
    price: 10,
    imageurl: "https://source.unsplash.com/flFd8L7_B3g",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
  {
    name: "Juice",
    ingredients: ["orange", "carrot", "apple"],
    price: 4,
    imageurl: "https://source.unsplash.com/IgGFNg-xPJs",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
  {
    name: "Burrito",
    ingredients: ["beans", "rice", "salsa"],
    price: 8,
    imageurl: "https://source.unsplash.com/Ce-YzEwLEh8",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
  {
    name: "Ice Cream",
    ingredients: ["vanilla", "chocolate", "sprinkles"],
    price: 6,
    imageurl: "https://source.unsplash.com/xtVjWVCiE-U",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
  {
    name: "Wrap",
    ingredients: ["grilled chicken", "lettuce", "tomato"],
    price: 9,
    imageurl: "https://source.unsplash.com/Spp1G283dow",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
  {
    name: "Soup",
    ingredients: ["vegetables", "broth", "noodles"],
    price: 5,
    imageurl: "https://source.unsplash.com/_y6A9bhILkM",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
  {
    name: "Fruit Salad",
    ingredients: ["melon", "grapes", "kiwi"],
    price: 6,
    imageurl: "https://source.unsplash.com/OPNC1UUSGj4",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
  {
    name: "Muffin",
    ingredients: ["blueberry", "flour", "sugar"],
    price: 3.5,
    imageurl: "https://source.unsplash.com/IM-1rvgCF-s",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
  {
    name: "Smoothie",
    ingredients: ["banana", "berries", "yogurt"],
    price: 5,
    imageurl: "https://source.unsplash.com/HDjExSGuWUw",
    uuid: uuidv4(),
    quantity: 0,
    isAdded: false,
  },
];

export default menuArray;
